# Import cấu hình từ file .env (ở thư mục hiện tại hoặc thư mục cha)
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

spring.application.name=SClubDB
server.forward-headers-strategy=framework
#spring.application.name=EXE101_S_Club

# Cau hinh ket noi PostgreSQL (Supabase)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Cau hinh Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cấu hình bảo mật Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile,https://www.googleapis.com/auth/calendar,https://www.googleapis.com/auth/spreadsheets,https://www.googleapis.com/auth/documents,https://www.googleapis.com/auth/drive.file
google.redirect-uri=${GOOGLE_REDIRECT_URI}
google.webhook-url=${GOOGLE_WEBHOOK_URL:https://yourdomain.com}

# Cấu hình Key bảo mật để tạo chuỗi JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION}

## PayOS Config
#payos.client-id=${PAYOS_CLIENT_ID:}
#payos.api-key=${PAYOS_API_KEY:}
#payos.checksum-key=${PAYOS_CHECKSUM_KEY:}
#
## URL cua Frontend de PayOS chuyen huong sau khi user tuong tac xong
#payos.return-url=http://localhost:3000/payment/success
#payos.cancel-url=http://localhost:3000/payment/cancel

# URL của Frontend Calendar để chuyển hướng sau khi liên kết Google Calendar thành công
app.frontend.calendar-url=${FRONTEND_CALENDAR_URL:http://localhost:5173/calendar}
